### PR TITLE
DTS-38319 | Release <10.1.0>

### PR DESCRIPTION
**Pull request by gipathak**
https://publicissapient.atlassian.net/browse/DTS-38319

### CODE REVIEW

**Review by Chittauri — COMMENTED** [review]
update the installation json ok fieldmapping structure as well

**Review by Chittauri — COMMENTED** [review]
in the ticket fix version is 10.1.0, and we have added the mongock files in 950, and update this https://publicissapient.atlassian.net/wiki/spaces/SPDS/pages/354058241/10.1.0+Mongock+Release confluence as well

**Comment by gipathak** [comment]
> update the installation json ok fieldmapping structure as well

Done

**Comment by gipathak** [comment]
> in the ticket fix version is 10.1.0, and we have added the mongock files in 950, and update this https://publicissapient.atlassian.net/wiki/spaces/SPDS/pages/354058241/10.1.0+Mongock+Release confluence as well

Done

**Review by shunaray — APPROVED** [review]

**Review by Chittauri — APPROVED** [review]

**Pull request merged**
